### ISSUE TITLE
binding static route

### ISSUE THREAD

**Issue by mdelgadov** [ewerspej/epj.RouteGenerator#1]
Congratulations on your plug in, I implemented it and works very well.
Gerald, on his video, mentions about automatically registering the routes, I did an approach like this:

```c#
foreach (var item in Routes.AllRoutes)
{
    Routing.RegisterRoute(item, Type.GetType(item));
}
```

which registers all routes.

Only one small detail:

How do you xaml bind the route without using strings?

My shell content looks like this:

```xml
<ShellContent ContentTemplate="{DataTemplate pages:MainPage}" />
```

I tried datatemplate pages:{}

I tried to create static but i'm new at this.

**Comment by ewerspej** [comment]
Hi @mdelgadov ,

thank you for your feedback.

I don't think that your approach using reflection will work, because when registering a route, you need to register the type of the class that needs to be instantiated for the given route, which usually is of type ContentPage or similar. You would need to have a way to figure out what the page type is.

What do you mean by "bind the route without using strings"? 

Cheers
