### ISSUE TITLE
[ios] AOT compatibility

### ISSUE THREAD

**Issue by yurkinh** [ewerspej/epj.RouteGenerator#2]
Hello,
Building an app in release mode for iOS produces such an error:
" error : Failed to AOT compile epj.RouteGenerator.dll, the AOT compiler exited with code 1"

Plugin lacks of AOT compatibility

**Comment by ewerspej** [comment]
Thank you, @yurkinh!

It's true, I still need to add AOT compatibility. The sample project currently has AOT disabled, but I will add AOT compatibility for the next release.

For the moment, you can disable AOT by adding something like the following to your *.csproj* file:

```xml
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
	  <RunAOTCompilation>False</RunAOTCompilation>
	</PropertyGroup>
```

This way you can disable AOT compilation temporarily until the issue is fixed.

**Comment by ewerspej** [comment]
As of now, Native AOT is not yet fully supported by .NET 8.0: https://github.com/dotnet/maui/issues/18839#issuecomment-1828006233

While this is the case, I cannot really test whether the library is AOT-compatible, although it should be already.
