### ISSUE TITLE
Warning When Using in a Non-Nullable Context

### ISSUE THREAD

**Issue by david-maw** [ewerspej/epj.RouteGenerator#5]
Nice work, thanks.

My MAUI code is non-nullable and so when I include RouteGenerator I get this warning:
`...ExtraRouteAttribute.cs(9,16,9,17): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context`

Probably just needs a `#nullable enable` at the top of the generated file.

**Comment by ewerspej** [comment]
Hi @david-maw,

thanks for bringing this up. I'm already aware of the issue. However, it's just a warning and the generated code cannot be modified and shouldn't be directly accessed.

Simply adding the `#nullable enable` and `#nullable disable` directives is not a solution for this, because the source generator isn't aware of the nullable context of the consumer project. This will be a problem, if the consumer project runs on C# versions prior to 8.0, where the directives were first introduced.

Since I don't want to break compatibility, I would need to find a way to check the global nullable context of the consumer project and use this information in the generator to decide whether to add those directives or not. While this should be possible, it doesn't seem to be trivial.

I know it's quite unlikely that any consumers use C# versions that are lower than 8.0, because people are switching to MAUI and other modern C# technologies, I don't know who is using the generator for which purposes. Otherwise, I have to make C# 8.0 a requirement for future releases, which means other consumers would have to stay on the current version.

I'll think about it, but I'm not making any promises.

Cheers!

**Comment by david-maw** [comment]
I'd assumed `#nullable enable` would just define that one specific generated file (`ExtraRouteAttribute.cs`) used nullable. I don't think whether the rest of the project happens to as well matters either way though obviously if it does `#nullable enable`
would have no effect.

That said, I have not looked at `ExtraRouteAttribute.cs`, as far as I can tell it does not get left behind on the `obj` folder after a build).

Good point about backward compatibility though, I didn't consider that, would simply inserting something like the code below work?
```
#if NET8_0_OR_GREATER
#nullable enable
#endif
``` 
I don't have a pre-8.0 .NET version to hand, but I imagine`NET8_0_OR_GREATER` simply isn't defined there.

Not that it's peculiar to this problem, but if you're of a mind to set [treatwarningsaserrors ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#treatwarningsaserrors) (some of us are blessed with a paranoid mindset and some unfortunate experiences) then even warnings become issues.

Anyway, thanks again for this, it's a very useful bit of code.

**Comment by ewerspej** [comment]
I created a preview version with a fix: https://www.nuget.org/packages/epj.RouteGenerator/1.0.2-preview1

Please check it out.

**Comment by david-maw** [comment]
Thanks, it worked fine as far as I can tell, and the warning is gone.

I agree about the case where people choose to run an explicit C# version that doesn't match the .NET version, though doing that always makes me nervous that I'll accidentally use some unsupported feature and not find out until runtime. I could not find an easy way of using the compiler version in code at build time.

**Comment by ewerspej** [comment]
@david-maw Great. Thanks. I'll run a few more checks and create a regular release version then.

About using higher C# versions than the default of the framework you're using: As long as you only use compiler-relevant features, which often are just syntactic sugar, there's usually nothing to be concerned about.

**Comment by david-maw** [comment]
Thank you @ewerspej , I'll switch to the regular release version once it is available 

As for mix-and-match C#, I agree with you, but I've found Sod's Law (or Murphy's Law if you're American) tend to conspire with "usually" in order to bite me in the proverbial extremity when it is least convenient. Thus my caution.

Thanks again for the quick fix.
